version: "3.4"

## This overrides frontend on the docker-compose.yml file when running run.local.sh, this is done so the frontend local container
## can be updated in real time while editing frontend code, it only needs to be restarted when changing the env variables
services:
  # ========
  # Frontend
  # ========
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: development-build-stage
    volumes:
      - ./frontend/src/:/frontend/src

  superset:
    container_name: superset
    command:
      - -c
      - |
        superset fab create-admin --username speedykom --firstname Superset --lastname Admin --email admin@superset.com --password speedykom
        superset db upgrade
        superset superset init
        FLASK_ENV=development flask run -p 8088 --with-threads --reload --debugger --host=0.0.0.0
