# Generated by Django 4.1.2 on 2023-05-15 06:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessChain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dag_name', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200)),
                ('data_source_name', models.CharField(max_length=200)),
                ('parquet_path', models.CharField(max_length=200)),
                ('dag_id', models.CharField(max_length=200)),
                ('schedule_interval', models.CharField(max_length=200)),
            ],
        ),
    ]
