# Generated by Django 4.2.1 on 2023-06-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processchain',
            name='state',
            field=models.CharField(default='active', max_length=200),
        ),
    ]
