# Generated by Django 4.2.1 on 2023-07-03 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_pipeline_remove_processchain_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipeline',
            old_name='user_name',
            new_name='description',
        ),
    ]
