# Generated by Django 4.2.1 on 2023-07-03 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_rename_user_name_pipeline_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processchain',
            old_name='dag_name',
            new_name='name',
        ),
    ]
