# Generated by Django 4.2.1 on 2023-07-03 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_rename_dag_name_processchain_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processchain',
            old_name='parquet_path',
            new_name='pipeline',
        ),
    ]
