# Generated by Django 4.2.1 on 2023-07-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0006_rename_parquet_path_processchain_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='processchain',
            name='user_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
