import os

KEYCLOAK_ADMIN_AUTH_URL = os.getenv("BACKEND_KEYCLOAK_ADMIN_AUTH_URL")
KEYCLOAK_ADMIN_CLIENT_ID = os.getenv("BACKEND_KEYCLOAK_ADMIN_CLIENT_ID")
KEYCLOAK_ADMIN_CLIENT_SECRET = os.getenv("BACKEND_KEYCLOAK_ADMIN_CLIENT_SECRET")
KEYCLOAK_ADMIN_USERNAME=os.getenv("BACKEND_KEYCLOAK_ADMIN_USERNAME")
KEYCLOAK_ADMIN_PASSWORD=os.getenv("BACKEND_KEYCLOAK_ADMIN_PASSWORD")

APP_USER_BASE_URL = os.getenv("BACKEND_APP_USER_BASE_URL")
APP_USER_ROLES = os.getenv("BACKEND_APP_USER_ROLES")
APP_REALM = os.getenv("BACKEND_APP_REALM")
APP_CLIENT_ID = os.getenv("BACKEND_APP_CLIENT_ID")
APP_CLIEND_UUID = os.getenv("BACKEND_APP_CLIEND_UUID")
APP_CLIENT_SECRET = os.getenv("BACKEND_APP_CLIENT_SECRET")
APP_SECRET_KEY = os.getenv("BACKEND_APP_SECRET_KEY")
BASE_URL = os.getenv("BACKEND_BASE_URL")
REST_REDIRECT_URI = os.getenv("BACKEND_REST_REDIRECT_URI")
