on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1.4.5
        with:
          working-directory: staging/frontend
      - name: Install frontend dependencies
        run: npm install
        working-directory: staging/frontend