on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v2
      - name: Use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          working-directory: staging/frontend
      - name: Install frontend dependencies
      - run: npm ci
      - run: npm run build --if-present
          working-directory: staging/frontend