on: [push]

jobs:
  # auto-request-review:
  #   name: Auto Request Review
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Request review based on files changes and/or groups the author belongs to
  #       uses: necojackarc/auto-request-review@v0.12.0
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         config:
  #           reviewers:
  #             defaults:
  #               -
  #           options:
  #             ignore_draft: false
  #         use_local: true

  frontend-integration:
    runs-on: ubuntu-latest
    name: Build and test frontend
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          working-directory: frontend
          cache-dependency-path: frontend/package-lock.json
          cache: "npm"
      - run: npm install
        working-directory: frontend
      - run: npm run pre-commit
        working-directory: frontend
      - run: npm run build --if-present
        working-directory: frontend

  backend-integration:
    runs-on: ubuntu-latest
    name: Build and test frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          architecture: "x64"
          working-directory: backend
          cache: "pip"
      - name: Install backend modules
        run: pip install -r requirements.txt
        working-directory: backend
      - name: Run migrations
        run: python manage.py migrate
        working-directory: backend
      - name: Run tests
        run: python manage.py test
        working-directory: backend
