name: CI/CD Dev Server
  
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Connect dev server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd Regional-Pandemic-Analytics/
            git pull
            docker-compose down --remove-orphans
            docker-compose build && clear
            docker-compose up -d