name: CI/CD Dev Server
  
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend:
    name: Buili Frontend
    runs-on: ubuntu-latest

    steps:
      

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build frontend
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          script: |
            cd Regional-Pandemic-Analytics/staging/frontend/
            npm install

      - name: connect dev server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd Regional-Pandemic-Analytics/
            git pull
            cd staging/frontend/