name: Build Pipeline
  
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Build and test frontend
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          working-directory: staging/frontend
      - run: npm install
        working-directory: staging/frontend
      - run: npm run build --if-present
        working-directory: staging/frontend

      - name: Connect dev server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd Regional-Pandemic-Analytics/
            git pull
            docker-compose build && clear
            docker-compose up -d