name: CI/CD Dev Server
  
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: connect dev server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd Regional-Pandemic-Analytics/
            git pull
            cd staging/frontend/
            docker-compose up