name: Build Pipeline

on:
  push:
    branches: [main]

jobs:
  call-frontend-integration:
    uses: ./.github/workflows/frontend-integration.yml

  call-backend-integration:
    uses: ./.github/workflows/backend-integration.yml

  deploy-dev:
    name: Deploy
    runs-on: devserver
    needs: [frontend-integration, backend-integration]
    steps:
      - uses: actions/checkout@v2
      - name: Connect to server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd Regional-Pandemic-Analytics/
            git pull
            make start-dev
