name: Build Pipeline
  
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Build Frontend
      - name: Build Frontend
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          working-directory: frontend
      - run: npm install
        working-directory: frontend
      - run: npm run build --if-present
        working-directory: frontend

      # Build Backend 
      - name: Build Backend 
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'
          working-directory: backend
      - name: Install backend modules
        run: pip install -r requirements.txt
        working-directory: backend
      - name: Run migrations
        run: python3 manage.py migrate
        working-directory: backend
      - name: Run tests
        run: python manage.py test
        working-directory: backend

      - name: Connect dev server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd Regional-Pandemic-Analytics/
            git pull
            ./run.sh