name: SCA

on:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  frontend-integration:
    runs-on: ubuntu-latest
    name: Frontend Integration
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          working-directory: frontend
          cache-dependency-path: frontend/package-lock.json
          cache: "npm"
      - run: npm install
        working-directory: frontend
      - run: npm i --package-lock-only
        working-directory: frontend
      - run: (npm audit --json || true ) > audit.json
        working-directory: frontend
        name: Audit packages
        env:
          CI: true
      - run: |
          (echo -e "Key\tName\tSeverity\tIsDirect\tTitle\tURL\tCVSS_Score"; 
          jq -r '
          .vulnerabilities | 
          to_entries[] | 
          [
            .key, 
            .value.name, 
            .value.severity, 
            .value.isDirect, 
            .value.via[0].title, 
            .value.via[0].url, 
            .value.via[0].cvss.score
          ] | 
          @tsv' audit.json) | column -t -s $'\t'
        name: Audit results
        working-directory: frontend

  backend-integration:
    runs-on: self-hosted
    name: Backend Integration
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          architecture: "x64"
          working-directory: backend
          cache: "pip"
      - name: Install backend modules
        run: pip install -r requirements.txt
        working-directory: backend
      - name: install pip-audit
        run: pip install pip-audit
        working-directory: backend
      - name: Audit results
        run: pip-audit || true
        working-directory: backend
