name: SCA

on:
  push:
    branches: [Feat/add-owasp-dependency-check]

jobs:
  frontend-integration:
    runs-on: ubuntu-latest
    name: Frontend Integration
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          working-directory: frontend
          cache-dependency-path: frontend/package-lock.json
          cache: "npm"
      - run: npm install
        working-directory: frontend
      - run: npm i --package-lock-only
        working-directory: frontend
      - run: npm audit --audit-level moderate
        name: Audit packages
        env:
          CI: true
      - run: npm run pre-commit
        working-directory: frontend
      - run: npm run build --if-present
        working-directory: frontend
